import Head from 'next/head'
import {Inter} from '@next/font/google'
import {Card} from "@chakra-ui/card";
import {
    Button,
    Center,
    Container,
    Flex,
    Text
} from "@chakra-ui/react";
import {ArrowForwardIcon, Icon} from "@chakra-ui/icons";
import {BsGithub} from "react-icons/bs";
import {RiLinkedinFill} from "react-icons/ri"
import Link from 'next/link';

export default function Home() {
    const intro = 'Hello I\'m Kyle';
    return (
        <>
            <Head>
                <title>Portfolio</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div>
                <Center>
                    <Container >
                        <Text className={'glitch'} fontWeight="bold" fontSize="3rem" width='fit-content' textColor='#33272a' data-text={intro}>
                            {intro}
                        </Text>
                        <Text fontSize="1rem">
                            A BSc Software Engineer graduate and multidisciplinary developer with a passion for web
                            development.
                        </Text>
                        <br/>
                        <Text fontSize="1rem">
                            Working with my hands to make magic happen on the internet. View my
                            <Link href='/projects'> <Button size='sm' variant='intro'> Projects </Button></Link>,
                            <Link href='/resume'> <Button size='sm' variant='intro'> Resume </Button></Link>,
                            <Link href='/about'><Button size='sm' variant='intro'>  About </Button></Link>.
                        </Text>
                        <Text>
                            You can send me an email at <Link href='/contact'><Button size='sm' variant='intro'> cunnisonkyle@gmail.com </Button></Link>.
                        </Text>
                        <br/>
                        <Text fontSize="1rem">
                            See more about me <ArrowForwardIcon className='bounce-icon-right'/>
                        </Text>
                        <Flex gap={3} alignItems='center'>
                            <Link href='https://www.linkedin.com/in/kyle-cunnison-995296132/' rel="noopener noreferrer" target="_blank"><Icon as={RiLinkedinFill} boxSize={6}></Icon></Link>
                            <Link href='https://github.com/neondyis' rel="noopener noreferrer" target="_blank"><Icon as={BsGithub} boxSize={6}/></Link>
                        </Flex>
                    </Container>
                </Center>
            </div>
        </>
    )
}
