import Head from 'next/head'
import {Inter} from '@next/font/google'
import {Card} from "@chakra-ui/card";
import {
    Button,
    Center,
    Container,
    Flex,
    Divider, IconButton, Link,
    Text
} from "@chakra-ui/react";
import {ArrowForwardIcon, ArrowRightIcon, Icon, PhoneIcon} from "@chakra-ui/icons";
import {BsGithub} from "react-icons/bs";
import {RiLinkedinFill} from "react-icons/ri"
import {MdLightMode, MdDarkMode} from "react-icons/md";

const inter = Inter({subsets: ['latin']})

export default function Home() {
    const intro = 'Hello I\'m Kyle Cunnison';
    return (
        <>
            <Head>
                <title>Portfolio</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <Center>
                    <Container >
                        <Text className={'glitch'} fontWeight="bold" fontSize="3rem" width='fit-content' textColor='#33272a' data-text={intro}>
                            {intro}
                        </Text>
                        <Text fontSize="1rem">
                            A BSc Software Engineer graduate and multidisciplinary developer with a passion for web
                            development.
                        </Text>
                        <br/>
                        <Text fontSize="1rem">
                            Working with my hands to make magic happen on the internet. View my
                            <Button size='sm' variant='intro'>  About </Button>,
                            <Button size='sm'  variant='intro'> Projects </Button> ,
                            <Button size='sm'  variant='intro'> Resume </Button> or send me an email at
                            <Button size='sm'  variant='intro'> cunnisonkyle@gmail.com </Button>.
                        </Text>
                        <br/>
                        <Text fontSize="1rem">
                            See more about me <ArrowForwardIcon className='bounce-icon-right'/>
                        </Text>
                        <Flex gap={3} alignItems='center'>
                            <Link href='https://www.linkedin.com/in/kyle-cunnison-995296132/' isExternal><Icon as={RiLinkedinFill} boxSize={6}></Icon></Link>
                             <Link href='https://github.com/neondyis' isExternal><Icon as={BsGithub} boxSize={6}/></Link>
                        </Flex>
                    </Container>
                </Center>
            </main>
        </>
    )
}
